{
    "name": "Elks Contacts",
    "version": "19.0.3.5",
    "category": "Contacts",
    "summary": "Manage Elks Member Contact Information",
    "author": "Danny Santiago",
    "website": "https://dannysantiago.info",
    "license": "LGPL-3",
    "depends": ["base", "base_import", "contacts", "hr", "hr_skills", "mail"],
    "data": [
        "security/ir.model.access.csv",
        "wizard/ballot_wizard_views.xml",
        "wizard/employee_merge_wizard_views.xml",
        "wizard/initiate_wizard_views.xml",
        "wizard/volunteer_link_wizard_views.xml",
        "wizard/volunteer_signup_wizard_views.xml",
        "wizard/suspension_wizard_views.xml",
        "wizard/drop_wizard_views.xml",
        "wizard/clms_import_wizard_views.xml",
        "views/elks_contact_views.xml",
        "views/elks_action.xml",
        "views/res_users_elks_views.xml",
        "views/res_partner_kanban_elks.xml",
        "views/res_partner_list_elks.xml",
        "views/res_partner_lodge_records_views.xml",
        "views/res_partner_officer_views.xml",
        "views/res_partner_search_elks.xml",
        "views/hr_employee_volunteer_views.xml",
        "views/elks_committee_views.xml",
        "views/elks_charitable_views.xml",
        "views/elks_membership_application_views.xml",
        "views/elks_menus.xml",
        "report/officer_roster_report.xml",
        "report/proposed_members_report.xml",
        "data/elks_committee_data.xml",
        "data/volunteer_training_data.xml",
        "data/elks_membership_application_data.xml",
        "data/elks_cron.xml",
    ],
    "assets": {
        "web.assets_backend": [
            "elkscontacts/static/src/css/elkscontacts.css",
        ],
    },
    "installable": True,
    "application": True,
    "pre_init_hook": "_pre_init_set_application_defaults",
}
